### ISSUE TITLE
Review and test existing RackHD deployment

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#106]
We will be acting as the consumers for the RackHD project where we focus on ensuring a seamless deployment of RackHD.

**Comment by clintonskitson** [comment]
In process.  Deploying with vagrant is good, getting stuck on a step for building boot images.

**Comment by clintonskitson** [comment]
Looking good now on deployment.  Waiting for steps for actually deploying something with RackHD that is useful as an example.

**Comment by kacole2** [comment]
@clintonskitson same here. was successfully able to boot up the Vagrant "monorail" server and all services come up as expected. Following the quick start, I can power on a `pxe-1` but it's left with a "no image found" after boot up. There needs to be some documentation on building a proper JSON file or whatever needs to be done next for a quick start. This would round out everything.

`8. Development Guide` should probably be renamed to something like `Administrator Guide` or `User Guide`. Using `Development Guide` makes it seem like you are going to start trolling through the internal code. 

I'm trying to perform some of the commands on the host but not receiving any replies
```
curl http://172.31.128.1:8080/api/1.1/workflows/library
curl: (52) Empty reply from server
```

**Comment by clintonskitson** [comment]
You can also one Joe in the Rackhd channel in the community for the latest
or if you have suggestions.

**Comment by kacole2** [comment]
ahh. good call

**Comment by heckj** [comment]
or you can @heckj mention me here and I'll respond. It is open source after all :-)

**Comment by clintonskitson** [comment]
Exactly =)
