### ISSUE TITLE
Update Isolator for Mesos 0.26

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#107]

**Comment by dvonthenen** [comment]
PR Merged:
https://github.com/emccode/mesos-module-dvdi/pull/64

Will be starting final build for 0.4.0 shortly.

**Comment by clintonskitson** [comment]
Thanks for the update @dvonthenen

**Comment by dvonthenen** [comment]
Closing this out since this went out with the 0.4.0 release
