### ISSUE TITLE
Develop plan to migrate code resources from Azure

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#108]

**Comment by drumulonimbus** [comment]
got access to the Azure-hosted stuff from Patrick/Magdy - looks like a bunch of allocated storage, three running virtual machines, two running "cloud services" (with a tonne more created but not running), plus a CDN endpoint, directory service and an automation account. looks like a lot of duplication - I'll touch base with Patrick and Magdy and see what resources are still in active use.

**Comment by drumulonimbus** [comment]
confirmed with Patrick that all virtual machines and storage have been purged from his account. nothing was found that needs to be migrated.

next steps, according to Patrick, are to engage with the Microsoft people and let them know that we won't be renewing the contract and have them delete the subscriptions and accounts.

**Comment by clintonskitson** [comment]
Ok great thank you
