### ISSUE TITLE
Discovery and Design of PaaS on Mesos with Volumes P1

### ISSUE THREAD

**Issue by jonasrosland** [emccode/roadmap#120]
What would it take to run stateful services together with PaaS systems like Deis, Flynn etc on Mesos?

**Comment by jonasrosland** [comment]
After some digging I've found the following, which of course might be biased and incorrect:

None of the PaaS systems I've look at include a simple to use platform to create stateful services with.
Most of them recommend creating it next to the PaaS system itself it, like we’ve done before with Mesos and Marathon.
What we end up with is stateful services running on Marathon/Mesos, and then PaaS systems like Deis and Flynn are used for the stateless apps.

I believe this is a great way of showing how you run multiple stacks for different use cases.

**Comment by clintonskitson** [comment]
Thanks for looking into it.  The purpose here to find a complimentary solution where a PaaS framework can sit on top of Mesos.  This means identifying an ideal PaaS frameworks for developers, but also an ideal scenario operations teams for leveraging Mesos at the scheduling layer.

In situations where we are talking about frameworks for things like HDFS, or distributed storage services where the lifecycle of the platform is decoupled this may make sense.  But when the persistent service lifecycle is coupled with the application being deployed, then this still means for simplicity that a PaaS framework should also cover spinning up a container or containers that supply persistent capabilities.

**Comment by jonasrosland** [comment]
Usually those services are spun up not by the PaaS itself but by other services. The services in Cloud Foundry is a good example here, where services (existing or new) are linked to applications, not spun up by the PaaS system itself.

**Comment by clintonskitson** [comment]
Agreed @jonasrosland, but a totally different model.  There are three ways we should be proceeding in this area 1) discovery of PaaS on Mesos 2) discovery of PaaS on Mesos with Volumes 3) Mesos frameworks such as Cassandra/Hadoop leveraging external volumes.  Thoughts?
