### ISSUE TITLE
Blog posts for Docker Machine Additions

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#13]

**Comment by kacole2** [comment]
have the first of 2 blog posts queued up. Will have to create the video first before publishing. I also have the binaries uploaded to my repo for people to use.

**Comment by clintonskitson** [comment]
Are the binaries based on a stable release from machine? I would reset to a
tag and cherry pick your commit over to make sure there is stability to the
base machine code.

**Comment by kacole2** [comment]
why? it's all experimental. latest is the greatest! <insert muhammad ali photo here>

**Comment by clintonskitson** [comment]
Experimental on experimental is always a great combo =) We want to avoid
publishing versions of Machine that are not officially tagged by Docker as
releases.  This minimizes moving parts, and helps in the case that someone
actually does run the extensions and runs into general problems with
Machine.

**Comment by clintonskitson** [comment]
For now, the e2c88d6
<https://github.com/docker/machine/commit/e2c88d6dac7e06db34c7f0e00c32801cc3adcbbf>
commit
from 0.4.1 would be the target unless there is good reason to not go that
route.

**Comment by kacole2** [comment]
#1 is done
http://blog.emccode.com/2015/09/26/make-docker-machine-do-anything-with-our-experimental-extensions/

**Comment by kacole2** [comment]
and another post:
http://blog.emccode.com/2015/10/01/use-docker-machine-and-compose-with-aws-ec2-to-automate-persistent-apps/
