### ISSUE TITLE
Enhance RackHD docker-machine driver for Rancher Demo

### ISSUE THREAD

**Issue by codenrhoden** [emccode/roadmap#142]
- [x] driver accepts SKU ID/name (a pool) instead of a NODE ID
- [x] driver picks a node from the SKU
- [x] driver tags node so it can't be picked again
- [x] driver applies workflow to node  (not sure if workflow needs to come from CLI param, or if it can be determined by more generic param--> e.g. --os=ubuntu becomes Task.OS.install.ubuntu)
- [x] driver powers on/reboots node
- [x] driver waits for OS install to complete, then hands of to higher layer for Docker config

milestone tracking is here: https://github.com/emccode/docker-machine-rackhd/milestone/1

**Comment by codenrhoden** [comment]
Updated description to add task list and link to milestone for docker-machine driver.

**Comment by codenrhoden** [comment]
Items 4 and 5 are actually both done by existing OS install workflows.

**Comment by wlan0** [comment]
Thanks for the update Travis! @codenrhoden :)

**Comment by codenrhoden** [comment]
v0.2.0 of the docker-machine driver has been released! https://github.com/emccode/docker-machine-rackhd/releases/tag/v0.2.0

This should serve as a perfect starting point for testing the driver. 0.2.x releases can happen for any bugfixes needed.

**Comment by heckj** [comment]
:fireworks: :package:
