### ISSUE TITLE
Video for Mesos and Docker Persistent Volumes

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#20]

**Comment by jonasrosland** [comment]
Video will be up in the beginning of next week.

**Comment by jonasrosland** [comment]
Video of the demo is online here, but will be moved to EMC CODE's playlist once we get access again: https://www.youtube.com/watch?v=WnVAS1raRik&feature=youtu.be

Title
"Docker container data persistence for PostgreSQL and Redis using REX-Ray with Mesos and Marathon"
