### ISSUE TITLE
Migrate rexray to rpm repository

### ISSUE THREAD

**Issue by drumulonimbus** [emccode/roadmap#24]
Build the binary version of rexray into the repo.

- ensure the build process bumps the version number in a sane fashion

**Comment by drumulonimbus** [comment]
specfile for the rexray RPM has now been submitted as a pull request to the master rexray repo - the CI system should now be able to build the RPM and push it to the bintray repo each build.

**Comment by clintonskitson** [comment]
This PR https://github.com/emccode/rexray/pull/69 brings in RPM support.
