### ISSUE TITLE
Prototype proposal for Cloud Formation+Docker+REX-Ray

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#31]

**Comment by drumulonimbus** [comment]
after discussing this with @clintonskitson, the proposal became more or less as follows:

- a user should be able to launch an instance using cloudformation
- the instance should have the current docker and rexray builds installed as part of the instantiation
- the user should be able to use the instance to start containers that take advantage of persistent storage provided by rexray
- the different steps of the process (starting the cloudformation stack, using rexray to attach storage to containers, etc) should be documented within github
- further documentation to be provided as a blog post
