### ISSUE TITLE
Video for Cloud Formation templates

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#36]

**Comment by drumulonimbus** [comment]
Video is finished, at least a first copy - ready for feedback. I'm pretty sure I can clean up the audio, but haven't figured out a way to export just the audio track.

https://www.youtube.com/watch?v=wIc8GmONRhE isn't publicly accessible

**Comment by clintonskitson** [comment]
Thanks @drumulonimbus.  Great to see your first video =)  So one thing to keep in mind here is that the videos tend  to be better received when they are limited in scope.  This would mean that the video is cut down to 4-6 minutes, and really only showing things done one way.

Second thing would be limiting distractions.  You want to end up with a video that doesn't expose custom things about your laptop.  So if you ahead of time set a certain portion of your screen real estate to contain the terminal window and browser, then during editing you can limit the output of the video to that section of the screen.

In terms of content, I think it would be best to simplify it a bit (which may make a 2-3 minute video).  I think showing how you can take the S3 URL that we advertise and paste that into the CF portal and have a working RR and Docker instance would be ideal.  The details around different options, or CLI methods would then be exposed via the repo and/or blog post.

**Comment by drumulonimbus** [comment]
ok, that's all very doable - my main concern is the S3 bucket. do we have an account for {code} buckets, one that isn't going away any time soon, and/or a naming structure for that sort of thing? I'm hesitant to build a video or blog post around a URL if we don't have a guarantee that that URL is never going to change.

**Comment by clintonskitson** [comment]
Not worried about it too much.. use your account for now.  The blog post can always be updated and the video description can refer to the github/blog post.

**Comment by drumulonimbus** [comment]
new version is up now. audio is at least 200% better, time cut down from >12 mins to 5m30s, scope cut down to just launching the instance from the web gui, and distractions from desktop stuff cut out completely. ready for review.

https://www.youtube.com/watch?v=d0qhF5kxJpQ - seems like the video quality might have dropped somehow though - I will re-upload if this version is acceptable.

**Comment by clintonskitson** [comment]
That was great man!

A coupe of things.. 1) make sure you encode it at 100, quality was too low
2) redo the last section of audio where you say don't run it in
production.. No need to say that.

Once done post the video to the articles channel for Kate so she can get it
to YouTube.

Assuming a short blog post referencing it is close as well..

**Comment by drumulonimbus** [comment]
video is finished and delivered
