### ISSUE TITLE
Milestone Proposal for Implementation of Docker Storage Scheduling

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#4]
Phase 2 & 3.. etc

**Comment by kacole2** [comment]
did Nathan just make my work so far moot??
https://github.com/docker/machine/issues/1765#issuecomment-137180940

**Comment by clintonskitson** [comment]
That's a chicken or the egg problem.  What if a plugin container is started
after a container that requires volumes?

**Comment by clintonskitson** [comment]
The other problem here would be that the mount would be occuring from within the container, which is the wrong context if you want the volumes to be made available to the host and thus a container that is requesting a volume.

**Comment by kacole2** [comment]
still hacking away at this...
1) I can get necessary Host/OS information to pass to the extension
2) I have successfully opened/read a json file from disk
3) I have successfully parsed the json to send it back to the install function
4) Tonight and next week i'm trying to figure out how an interface is used to pass parameters into functions of different files that have the same function name. It's what I would like to do, but i'm not exactly sure how it's being done or what it's called. Hoping someone can help me navigate this next week. Once this part is done then the basic functionality should be done. Then it's down to creating error handling, logging, and maybe some tests.

**Comment by clintonskitson** [comment]
Milestone proposal will be based from prototype examples

**Comment by kacole2** [comment]
here is the current progress..
https://github.com/docker/machine/compare/master...kacole2:extensions

**Comment by clintonskitson** [comment]
Way to go, nice use of the driver/adapter pattern.  I could see a `generic` adapter at some point fitting in there nicely.

**Comment by kacole2** [comment]
@clintonskitson it still doesn't work... been banging my head on it for hours... lets set aside a time for us to go over it
