### ISSUE TITLE
Scope the changes to enable a remote volume driver

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#50]

**Comment by vaibhavkhanduja** [comment]
Nice initiative ... please check libstorage  - https://github.com/openSUSE/libstorage from SuSE, seems to be very comprehensive though I have not tried.

**Comment by clintonskitson** [comment]
@vaibhavkhanduja Although similar in naming, I don't believe they are achieving the same purpose
https://en.opensuse.org/Portal:Libstorage.  The LibStorage we are referring to does deal with creating and mounting filesystems.  However, there are other missing pieces to the puzzle of attaching remote disks, ie. introspection of who am I, issuing API calls to map, and then discover local disks.  These things as an example, must be abstracted among storage platforms.

**Comment by clintonskitson** [comment]
Work to take place here after RR 0.2 delivery

**Comment by vaibhavkhanduja** [comment]
I may not sound very pro EMC here, but I always thought EMC portfolio has a missing SDS piece, which can serve all kinds of storage - file, block, object and also file-system. IBM has it GPFS, Redhat got Ceph (quite advance distributed file-system with implementing "Crush"). IBM even has RDMA, iSER support :( 

Anyways, good luck ... would like to see your specs when available ..
