### ISSUE TITLE
REX-Ray artifact implementation

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#53]

**Comment by clintonskitson** [comment]
@drumulonimbus let's communicate to the team the details about how to get the artifacts to the proper place and then update the README for the proper usage of the repositories

**Comment by akutz** [comment]
Hi @clintonskitson, 

This was not worked on in concert with me, so I need first to review it to ensure that it will work with Travis-CI. As it is I'm using Travis-CI to push artifacts to the GH release area as that's supported by Travis-CI.

**Comment by clintonskitson** [comment]
Ok, @drumulonimbus let's work with @akutz to ensure we are able to do our package management based installs from our public repo in addition to storing our releases at GH.

**Comment by akutz** [comment]
@drumulonimbus is using BitBucket, right? I'm familiar with Artifactory and Maven repos, and I investigated Travis to see what it supports. I have to ask why we're not using GH release hooks for our releases since our code is stored on GH and Travis-CI has first class support for GH releases.

**Comment by drumulonimbus** [comment]
hey guys - zero problem pushing artifacts to the repo. we're using bintray, not bitbucket, and pushing artifacts is as simple as calling 'curl' somewhere after the build has been completed.

**Comment by drumulonimbus** [comment]
I was under the impression that the CI server that I would be tying into was the CI server that *all* emccode projects would eventually be migrated to, as part of the 'justdoit' devops pipeline project that we all agreed upon at the last offsite meeting...?

**Comment by akutz** [comment]
And I was under the impression that I had charge of designing this pipeline and EMC{code}'s DevOps charter in general per @clintonskitson. I think there is some disconnect there, and I'm not trying to step on your toes. And I bet @clintonskitson meant bintray, not bitbucket. Bintray is a fine choice, but I'm curious about the CI server to which you're referring. Is it Travis? Because that's what REX-Ray is using per @clintonskitson's suggestion, so I'm assuming it is the same system to which you're referring.

**Comment by drumulonimbus** [comment]
as far as I know, the design and implementation of the CI server was assigned to Magdy.

**Comment by akutz** [comment]
Do you know if Travis-CI is the system of choice?

**Comment by drumulonimbus** [comment]
The last update I saw was on July 7th, in which a chart was delivered comparing the features of Travis-CI, Shippable, Codeship and Jenkins, with a decision to be ostensibly made by the team. I don't know that that decision was ever made, but I haven't seen any further motion since. It would seem that through your work you have made that discussion unnecessary. :)

**Comment by akutz** [comment]
It seems so...

**Comment by clintonskitson** [comment]
Since `justdoit` is a work in progress still, RR is pursuing alternate options.  I believe that it will serve as a good lighthouse to influence decisions in the `justdoit` project, but there does not necessarily need to be alignment at this point.  @akutz the direction was specific to this project.

**Comment by clintonskitson** [comment]
So that leaves the question, how best to get the output of Travis to an artifact repository?  As simple as a curl command that we need to include @drumulonimbus

**Comment by akutz** [comment]
Hi @clintonskitson,

Actually there is no question as Travis-CI has built in methods for this madness to which I alluded above:

* [Travis-CI and GitHub Releases](http://docs.travis-ci.com/user/deployment/releases/)
* [Travis-CI and Bintray](http://docs.travis-ci.com/user/deployment/bintray/)

Here's a [complete list](http://docs.travis-ci.com/user/deployment/) of artifact repositories for which Travis-CI includes support.

**Comment by akutz** [comment]
Hi @clintonskitson, @drumulonimbus,

By the way, this doesn't preclude doing both. We could upload ALL artifacts built from commits to master to bintray after each successful build and only upload the ones built from a release tag to GH releases (as well as to bintray). What's our bintray information?

**Comment by drumulonimbus** [comment]
Hey @akutz,

Good call – maybe all artifacts could go to a private repo on bintray and only the release-tagged builds to a public one?

Re: info – there’s an “organization” on bintray called ‘emccode’; add yourself a user there and let me know your username and I’ll add you to the organization as a publisher.

Cheers,
- Drew.

--
Drew Smith, Cloud Applications Engineer
Emerging Technologies Division | EMC2

**Comment by akutz** [comment]
Hi @drumulonimbus,

I'd like to push at least a subset of *all* artifacts to a public repo on bintray. The reason being is that the GH release page will only be updated with artifacts when we tag a commit as a release. I don't want to tag every single commit to master obviously. However, it would still be useful for people to be able to download pre-built binaries for each commit to master. I was thinking bintray could serve that purpose.

**Comment by drumulonimbus** [comment]
Hey @akutz,

I’m fine with that also, just so long as we name that repo something (anything) other than ‘stable’. ☺

Cheers,
- Drew.

--
Drew Smith, Cloud Applications Engineer
Emerging Technologies Division | EMC2

**Comment by akutz** [comment]
Hi @drumulonimbus,

I was thinking `unstable` in fact :)

**Comment by akutz** [comment]
I joined the org. Would sure appreciate the pub perms so I can kick these tires! Thanks!

**Comment by drumulonimbus** [comment]
Added you about fifteen seconds after I got the notification email. ☺

Cheers,
- Drew.

--
Drew Smith, Cloud Applications Engineer
Emerging Technologies Division | EMC2

**Comment by akutz** [comment]
Hi @drumulonimbus,

Would you please create a generic repo named `rexray` and give me perms on it? I can add the avatar and description. Or a generic repo for non-RPMs called `unstable` where we can place any non-RPM uploads for various projects? Thanks! While you're at it you may as well create a repo named `stable` as well for releases.

**Comment by drumulonimbus** [comment]
Hey @akutz,

While we’re both working on it, why don’t you just use repositories local to your own user “akutz”, and then we’ll just change that to the final repositories once the hierarchy has been finalized?

Cheers,
- Drew.

--
Drew Smith, Cloud Applications Engineer
Emerging Technologies Division | EMC2

**Comment by akutz** [comment]
Like this? https://bintray.com/akutz/generic/rexray/view

**Comment by clintonskitson** [comment]
This PR https://github.com/emccode/rexray/pull/69 brings in artifact support.
