### ISSUE TITLE
Develop External Extensibility interfaces with Docker Machine

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#8]

**Comment by kacole2** [comment]
the basic functionality is currently working. it will take in a series of key:value pairs and pass those to the installer interface. Here is the latest code.
https://github.com/kacole2/machine/tree/extensions

files of importance:
```
machine/libmachine/host.go
machine/libmachine/extension/extension.go
machine/libmachine/extension/rexray.go

**Comment by kacole2** [comment]
latest commit has updated extension interface and rexray configuration... 
https://github.com/kacole2/machine/tree/extensions

tomorrow will be refactoring by adding things to utils.go and generic.go to make them interchangeable between extensions

**Comment by kacole2** [comment]
done. https://github.com/kacole2/machine/tree/extensions

need to squash commits, rebase, and PR
